# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19b3c191d34ec50427369e21ae51897894dd352d718517b32611f394549cd2b2be150be8eee502657a86e4e03b875d92f0c34218bff96bc2355a526af95519d

test:
  secret_key_base: b16bf4ad2b47e985e9a123ec3e19732ab1ed31acfb929e8674376532671ecbc0cdf63ab4c3e818af7397dbe8c82f202c0df01a1b5238bb6312988577e88c45d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
